name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Clean install dependencies
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install

  lint:
    runs-on: macos-latest
    needs: install
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run lint
        run: npm run lint

  unit-test:
    runs-on: macos-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run unit tests
        run: npm test

  integration-test:
    runs-on: macos-latest
    needs: unit-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run integration tests
        run: echo "Running integration tests..."

  e2e-test:
    runs-on: macos-latest
    needs: integration-test
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run E2E tests
        run: echo "Running E2E tests..."

  only-canary-test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Only Canary tests
        if: ${{ env.ENV_TARGET == 'canary' }}
        run: echo "Running Canary tests..."
