name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      # Vérifie le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure la version de Node.js avec cache npm
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'npm'

      # Installe les dépendances avec npm ci
      - name: Install dependencies
        run: npm ci

      # Exécute le linting
      - name: Run linting
        run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: validate
    steps:
      # Vérifie le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure la version de Node.js avec cache npm
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'npm'

      # Installe les dépendances avec npm ci
      - name: Install dependencies
        run: npm ci

      # Compile le projet
      - name: Build the project
        run: npm run build

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Vérifie le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure la version de Node.js avec cache npm
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'npm'

      # Installe les dépendances avec npm ci
      - name: Install dependencies
        run: npm ci

      # Exécute les tests
      - name: Run tests
        run: npm test

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    steps:
      # Vérifie le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure la version de Node.js avec cache npm
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'npm'

      # Logique de release
      - name: Release project
        run: echo "Release logic here" # Remplacez par vos scripts de release

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: release
    steps:
      # Vérifie le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure la version de Node.js avec cache npm
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'npm'

      # Logique de déploiement
      - name: Deploy project
        run: echo "Deploy logic here" # Remplacez par vos scripts de déploiement
